use_frameworks!

platform :ios, '10.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'MarsUIKit_Example' do
  pod 'MarsUIKit', :path => '../'
  
  # RxSwift
  pod 'RxSwift'
  # RxCocoa
  pod 'RxCocoa'
  # SVProgressHUD
  pod 'SVProgressHUD'
  
  # Kingfisher
  pod 'Kingfisher'
  
  # KafkaRefresh
  pod 'KafkaRefresh'
  # MJRefresh
  pod 'MJRefresh'
  # DZNEmptyDataSet
  pod 'DZNEmptyDataSet'
  
  # SwiftMessages
  pod 'SwiftMessages'
  # Toaster
  pod 'Toaster'
  # Toast_Swift
  pod 'Toast-Swift', '~> 5.0.1'
  # OverlayController
  pod 'OverlayController'
  # SVGA: /Pods/SVGAPlayer/Source/pbobjc/Svga.pbobjc.m: Conflicting types for 'OSAtomicCompareAndSwapPtrBarrier'
  pod 'SVGAPlayer'
  #pod 'SSZipArchive', '~> 2.1.4'
  #pod 'Protobuf', '~> 3.4'
  
  target 'MarsUIKit_Tests' do
    inherit! :search_paths
  end
end
