use_frameworks!

platform :ios, '11.0'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'MarsUIKit_Example' do
  pod 'MarsUIKit', :path => '../'
  # EmptyDataSet
  pod 'MarsUIKit/EmptyDataSet', :path => '../'
  # RxEmptyDataSet
  pod 'MarsUIKit/RxEmptyDataSet', :path => '../'
  # RxMJRefresh
  pod 'MarsUIKit/RxMJRefresh', :path => '../'
  # RxKafkaRefresh
  pod 'MarsUIKit/RxKafkaRefresh', :path => '../'
  # OverlayView
  pod 'MarsUIKit/OverlayView', :path => '../'
  # Messages
  pod 'MarsUIKit/Messages', :path => '../'
  # Toast
  pod 'MarsUIKit/Toast', :path => '../'
  # SVGA
  pod 'MarsUIKit/SVGA', :path => '../'
  
  target 'MarsUIKit_Tests' do
    inherit! :search_paths
  end
end
